### ISSUE TITLE
Upgrade to px-vis-spark ^1.0.0

### ISSUE THREAD

**Issue by davidsteinberger** [PredixDev/px-kpi#2]
I see several issues w/ the outdated px-vis-spark version. Could you update to a more recent version like ^1.0.0?

**Comment by mdwragg** [comment]
Hi, can you follow the issue template and explain what the issue is please?

**Comment by davidsteinberger** [comment]
I did not get the template populated. Nevertheless here's the proper description:

## Expected behavior and actual behavior:

px-kpi imports [px-vis-spark](https://github.com/PredixDev/px-vis-spark) in version ^0.2.0.
This one has issues like:

- html imports that do not exist
- script tags outside of the dom-module definition

The first one is fixed in v1.0.0, for the other one I opened https://github.com/PredixDev/px-vis-spark/issues/3.

## Steps to reproduce the problem:

Use the component in a browser that supports shadow dom and lazy load polymer.

## Environment (_component version number, Browser (including version), operating system, hardware, etc_):

0.2.4, Chrome, Mac

**Comment by davidsteinberger** [comment]
Could the deps of `<px-kpi>` be updated to px-vis v1.0.0?

**Comment by randyaskin** [comment]
Looks like @benoitjchevalier did this two weeks ago in v1.0.0 of px-kpi.
